---
title: "Descriptive Statistics on IPIP-NEO-120 Johnson Dataset"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment=NA, fig.width=15, fig.height=6)

library("psych")

source("preparedata.R")
```

## Big Five Dimensions and Facets (USA, male and female, 18 to 75 years)

### Big Five Dimensions

````{r}
describe(data.usa.18to75[, c("NEUROTICISM","EXTRAVERSION", "OPENESS", "AGREEABLENESS", "CONSCIENTIOUSNESS")])

````

### Extra myKMU Dimensions

````{r}
describe(data.usa.18to75[, c("TEAMWORK","CREATIVITY")])

````

### Facets

#### Neuroticism facets

````{r}
describe(data.usa.18to75[, c("ANXIETY", "ANGER", "DEPRESSION", "SELFCONSCIOUSNESS", "IMMODERATION", "VULNERABILITY")])
````

#### Extraversion facets

````{r}
describe(data.usa.18to75[, c("FRIENDLINESS", "GREGARIOUSNESS", "ASSERTIVENESS", "ACTIVITYLEVEL", "EXCITEMENTSEEKING", "CHEERFULNESS")])
````

#### Openness to experience facets

````{r}
describe(data.usa.18to75[, c("IMAGINATION", "ARTISTICINTERESTS", "EMOTIONALITY", "ADVENTUROUSNESS", "INTELLECT", "LIBERALISM")])
````

#### Agreeableness facets

````{r}
describe(data.usa.18to75[, c("TRUST", "MORALITY", "ALTRUISM", "COOPERATION", "MODESTY", "SYMPATHY")])
````

#### Conscientiousness facets

````{r}
describe(data.usa.18to75[, c("SELFEFFICACY", "ORDERLINESS", "DUTIFULNESS", "ACHIEVEMENTSTRIVING", "SELFDISCIPLINE", "CAUTIONESS")])
````

### Big Five and Facets Boxplots

````{r}
boxplot(data.usa.18to75[, c("NEUROTICISM","EXTRAVERSION", "OPENESS", "AGREEABLENESS", "CONSCIENTIOUSNESS")],
          main = "Big Five Dimensions",
          ylab = "Raw scale values"
        )

boxplot(data.usa.18to75[, c("ANXIETY", "ANGER", "DEPRESSION", "SELFCONSCIOUSNESS", "IMMODERATION", "VULNERABILITY")],
          main = "Neuroticism Facets",
          ylab = "Raw scale values"
        )

boxplot(data.usa.18to75[, c("FRIENDLINESS", "GREGARIOUSNESS", "ASSERTIVENESS", "ACTIVITYLEVEL", "EXCITEMENTSEEKING", "CHEERFULNESS")],
          main = "Extraversion Facets",
          ylab = "Raw scale values"
        )

boxplot(data.usa.18to75[, c("IMAGINATION", "ARTISTICINTERESTS", "EMOTIONALITY", "ADVENTUROUSNESS", "INTELLECT", "LIBERALISM")],
          main = "Openness to Experience Facets",
          ylab = "Raw scale values"
        )

boxplot(data.usa.18to75[, c("TRUST", "MORALITY", "ALTRUISM", "COOPERATION", "MODESTY", "SYMPATHY")],
          main = "Agreeableness Facets",
          ylab = "Raw scale values"
        )

boxplot(data.usa.18to75[, c("SELFEFFICACY", "ORDERLINESS", "DUTIFULNESS", "ACHIEVEMENTSTRIVING", "SELFDISCIPLINE", "CAUTIONESS")],
          main = "Conscientiousness Facets",
          ylab = "Raw scale values"
        )
````